# -------- Build Stage --------
FROM node:24.10.0-slim AS build

# Set working directory
WORKDIR /app

# Copy dependency manifests first (for caching)
COPY package*.json ./

# Install production dependencies (Install dependencies as root, switch to non-root after)
RUN npm ci --only=production

# Create non-root user in build stage
RUN useradd -m appuser

# Copy all source code
COPY src ./src

RUN chown -R appuser:appuser /app

#find its UID by adding a temporary command:
#RUN id -u appuser

# Switch to non-root user
USER appuser

# -------- Production Stage --------
#FROM node:24.10.0-slim AS production
FROM gcr.io/distroless/nodejs24 AS production

# Set working directory
WORKDIR /app

# Copy only production dependencies from build stage
COPY --from=build /app/node_modules ./node_modules

# Copy source code
#Copy from build stage rather than local host to avoid accidentally including unwanted local files. Consistent build, independent of local machine state.
COPY --from=build /app/src ./src

# Run container as the same UID as the build-stage user
# In Debian-based node:slim, useradd creates UID 1000 by default
USER 1000

# Set environment variables (optional defaults)
ENV APP_NAME="Express API"
ENV PORT=3000

# Expose port
EXPOSE ${PORT}

# Optional: Healthcheck for production monitoring
HEALTHCHECK --interval=30s --timeout=5s --start-period=5s \
  CMD curl -f http://localhost:${PORT}/ || exit 1

# Start application
# Distroless has no node binary — not call node manually - distroless already sets node as the entrypoint internally.
CMD ["src/index.js"]