# -------- Build Stage --------
FROM node:24.10.0-slim AS build

# Set working directory
WORKDIR /app

# Copy dependency manifests first (for caching)
COPY package*.json ./

# Install all dependencies (dev + prod) (typescript is in devDependencies)
RUN npm ci

# Copy all source code
COPY . .

# Build application
CMD ["npm", "run", "dev"]